---
abstract: 'Catalyst based application'
author:
  - 'Curtis Poe'
build_requires:
  App::Info::RDBMS::SQLite: 0.55
  ExtUtils::MakeMaker: 6.42
  Test::Most: 0.21
  Test::WWW::Mechanize::Catalyst: 0.51
  WWW::Mechanize: 1.60
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Escape
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  IO::Prompt: 0.99.4
  Text::CSV::Encoded: 0.08
  Text::Unaccent: 1.08
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Authentication::Realm::SimpleDB: 0
  Catalyst::Controller::HTML::FormFu: 0
  Catalyst::Helper::View::TT: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::Cache: 0.08
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.80007
  Config::General: 0
  DBD::SQLite: 1.25
  DBIx::Class::EncodedColumn: 0.00002
  DBIx::Class::TimeStamp: 0.12
  HTML::FormFu: 0.05001
  HTML::FormFu::Model::DBIC: 0.05002
  HTML::SimpleLinkExtor: 1.23
  Number::Format: 1.72
  parent: 0
resources:
  bugtracker: http://github.com/Ovid/Escape-/issues
  license: http://opensource.org/licenses/artistic-license-2.0.php
  repository: http://github.com/Ovid/Escape-/tree/master
version: 0.05
