---
abstract: 'Catalyst based application'
author:
  - 'Curtis Poe'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Escape
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Helper::View::TT: 0
  Catalyst::Plugin::Cache: 0.08
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.80007
  Config::General: 0
  DBIx::Class::TimeStamp: 0.12
  HTML::SimpleLinkExtor: 1.23
  Number::Format: 1.72
  Text::Unaccent: 1.08
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
